# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/school/IgnoringComments

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/school/IgnoringComments

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/school/IgnoringComments/CMakeFiles /mnt/e/school/IgnoringComments//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/school/IgnoringComments/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IgnoreComments

# Build rule for target.
IgnoreComments: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IgnoreComments
.PHONY : IgnoreComments

# fast build rule for target.
IgnoreComments/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/build
.PHONY : IgnoreComments/fast

CommentIdentifierDFA.o: CommentIdentifierDFA.cpp.o
.PHONY : CommentIdentifierDFA.o

# target to build an object file
CommentIdentifierDFA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/CommentIdentifierDFA.cpp.o
.PHONY : CommentIdentifierDFA.cpp.o

CommentIdentifierDFA.i: CommentIdentifierDFA.cpp.i
.PHONY : CommentIdentifierDFA.i

# target to preprocess a source file
CommentIdentifierDFA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/CommentIdentifierDFA.cpp.i
.PHONY : CommentIdentifierDFA.cpp.i

CommentIdentifierDFA.s: CommentIdentifierDFA.cpp.s
.PHONY : CommentIdentifierDFA.s

# target to generate assembly for a file
CommentIdentifierDFA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/CommentIdentifierDFA.cpp.s
.PHONY : CommentIdentifierDFA.cpp.s

FileHandler.o: FileHandler.cpp.o
.PHONY : FileHandler.o

# target to build an object file
FileHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/FileHandler.cpp.o
.PHONY : FileHandler.cpp.o

FileHandler.i: FileHandler.cpp.i
.PHONY : FileHandler.i

# target to preprocess a source file
FileHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/FileHandler.cpp.i
.PHONY : FileHandler.cpp.i

FileHandler.s: FileHandler.cpp.s
.PHONY : FileHandler.s

# target to generate assembly for a file
FileHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/FileHandler.cpp.s
.PHONY : FileHandler.cpp.s

StringIdentifierDFA.o: StringIdentifierDFA.cpp.o
.PHONY : StringIdentifierDFA.o

# target to build an object file
StringIdentifierDFA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/StringIdentifierDFA.cpp.o
.PHONY : StringIdentifierDFA.cpp.o

StringIdentifierDFA.i: StringIdentifierDFA.cpp.i
.PHONY : StringIdentifierDFA.i

# target to preprocess a source file
StringIdentifierDFA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/StringIdentifierDFA.cpp.i
.PHONY : StringIdentifierDFA.cpp.i

StringIdentifierDFA.s: StringIdentifierDFA.cpp.s
.PHONY : StringIdentifierDFA.s

# target to generate assembly for a file
StringIdentifierDFA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/StringIdentifierDFA.cpp.s
.PHONY : StringIdentifierDFA.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IgnoreComments.dir/build.make CMakeFiles/IgnoreComments.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IgnoreComments"
	@echo "... CommentIdentifierDFA.o"
	@echo "... CommentIdentifierDFA.i"
	@echo "... CommentIdentifierDFA.s"
	@echo "... FileHandler.o"
	@echo "... FileHandler.i"
	@echo "... FileHandler.s"
	@echo "... StringIdentifierDFA.o"
	@echo "... StringIdentifierDFA.i"
	@echo "... StringIdentifierDFA.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

